// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhU3gKo-RpzcJ1HgBCc6sLD0dbzBGArUY',
    appId: '1:91500286107:web:c629bf72ef76d05fe8b63e',
    messagingSenderId: '91500286107',
    projectId: 'geoscanner-e6eff',
    authDomain: 'geoscanner-e6eff.firebaseapp.com',
    storageBucket: 'geoscanner-e6eff.appspot.com',
    measurementId: 'G-ZXNRCRMDSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsBWDNSlrVGou4iG4iwY3vvzO38gMuyOI',
    appId: '1:91500286107:android:3b65943678e88b1ee8b63e',
    messagingSenderId: '91500286107',
    projectId: 'geoscanner-e6eff',
    storageBucket: 'geoscanner-e6eff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX7N5O0p6wMoqvbJOaAOpc5-fTP5PtPZQ',
    appId: '1:91500286107:ios:fe86fd664cac5830e8b63e',
    messagingSenderId: '91500286107',
    projectId: 'geoscanner-e6eff',
    storageBucket: 'geoscanner-e6eff.appspot.com',
    iosBundleId: 'com.example.geoscanner',
  );
}
