name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'project_website/**' # deploy only when changes are made to the project_website directory

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create config.js
      run: |
        echo "export default {" > ./project_website/scripts/config.js
        echo "  MAPBOX_ACCESS_TOKEN: '$MAPBOX_ACCESS_TOKEN'," >> ./project_website/scripts/config.js
        echo "  FIREBASE_API_KEY: '$FIREBASE_API_KEY'" >> ./project_website/scripts/config.js
        echo "};" >> ./project_website/scripts/config.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./project_website

    env:
      MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
